1.1. Load the wine dataset from the given ‘wine.csv’ file into a
variable (say data).

In [ ]:
import pandas as pd
import numpy as np
data = pd.read_csv('/content/wine.csv', skiprows = [0])
print(data)
data.shape

     1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29   5.64  1.04  \
0    1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
1    1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
2    1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
3    1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
4    1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97   6.75  1.05   
..  ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
172  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
173  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
174  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
175  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
176  3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

     3.92  1065  
0    3.40  1050  
1    3.17  1185  
2    3.45  1480  
3  

(177, 14)

In [ ]:
print(data.size)

2478


1.2. From the variable, extract the numerical information into a new
variable, say scores.

In [ ]:
scores = pd.read_csv('/content/wine.csv')
print(scores)

     Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0       1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1       1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2       1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3       1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4       1    13.24        2.59  2.87  21.0  118     2.80        2.69   
..    ...      ...         ...   ...   ...  ...      ...         ...   
173     3    13.71        5.65  2.45  20.5   95     1.68        0.61   
174     3    13.40        3.91  2.48  23.0  102     1.80        0.75   
175     3    13.27        4.28  2.26  20.0  120     1.59        0.69   
176     3    13.17        2.59  2.37  20.0  120     1.65        0.68   
177     3    14.13        4.10  2.74  24.5   96     2.05        0.76   

     Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                    0.28     2.29       5.64  1.04  3.92     1065

1.3. Calculate the row-wise,column-wise, and overall mean, median,
mode, and standard deviation of the dataset. 

In [ ]:
print("Mean:Computed column-wise:");
meanData = scores.mean();
print(meanData);

Mean:Computed column-wise:
Wine                      1.938202
Alcohol                  13.000618
Malic.acid                2.336348
Ash                       2.366517
Acl                      19.494944
Mg                       99.741573
Phenols                   2.295112
Flavanoids                2.029270
Nonflavanoid.phenols      0.361854
Proanth                   1.590899
Color.int                 5.058090
Hue                       0.957449
OD                        2.611685
Proline                 746.893258
dtype: float64


In [ ]:
print("Median:Computed column-wise:");
medianData = scores.median();
print(medianData);

Median:Computed column-wise:
Wine                      2.000
Alcohol                  13.050
Malic.acid                1.865
Ash                       2.360
Acl                      19.500
Mg                       98.000
Phenols                   2.355
Flavanoids                2.135
Nonflavanoid.phenols      0.340
Proanth                   1.555
Color.int                 4.690
Hue                       0.965
OD                        2.780
Proline                 673.500
dtype: float64


In [ ]:
print("Mode:Computed column-wise:");
modeData = scores.mode();
print(modeData);

Mode:Computed column-wise:
   Wine  Alcohol  Malic.acid   Ash   Acl    Mg  Phenols  Flavanoids  \
0   2.0    12.37        1.73  2.28  20.0  88.0      2.2        2.65   
1   NaN    13.05         NaN  2.30   NaN   NaN      NaN         NaN   
2   NaN      NaN         NaN   NaN   NaN   NaN      NaN         NaN   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.26     1.35        2.6  1.04  2.87    520.0  
1                  0.43      NaN        3.8   NaN   NaN    680.0  
2                   NaN      NaN        4.6   NaN   NaN      NaN  


In [ ]:
print("Standard deviation:Computed column-wise:");
stdData = scores.std();
print(stdData);

Standard deviation:Computed column-wise:
Wine                      0.775035
Alcohol                   0.811827
Malic.acid                1.117146
Ash                       0.274344
Acl                       3.339564
Mg                       14.282484
Phenols                   0.625851
Flavanoids                0.998859
Nonflavanoid.phenols      0.124453
Proanth                   0.572359
Color.int                 2.318286
Hue                       0.228572
OD                        0.709990
Proline                 314.907474
dtype: float64


In [ ]:
print("Mean:Computed row-wise:");
meanData = scores.mean(axis=1);
print(meanData);

Mean:Computed row-wise:
0       89.000000
1       85.364286
2       95.915714
3      117.963571
4       64.977857
          ...    
173     63.875714
174     65.124286
175     72.444286
176     72.640714
177     51.471429
Length: 178, dtype: float64


In [ ]:
print("Median:Computed row-wise:");
medianData = scores.median(axis=1);
print(medianData);

Median:Computed row-wise:
0      2.930
1      2.705
2      2.990
3      3.470
4      2.835
       ...  
173    2.725
174    2.740
175    2.630
176    2.480
177    2.870
Length: 178, dtype: float64


In [ ]:
from scipy.stats import mode
print("Mode:Computed row-wise:");
modeData = mode(scores, axis=1).mode;
print(modeData);

Mode:Computed row-wise:
[[0.28]
 [0.26]
 [0.3 ]
 [0.24]
 [0.39]
 [0.34]
 [0.3 ]
 [0.31]
 [0.29]
 [0.22]
 [0.22]
 [0.26]
 [0.29]
 [0.43]
 [0.29]
 [0.3 ]
 [0.33]
 [0.4 ]
 [0.32]
 [0.17]
 [0.24]
 [2.41]
 [0.27]
 [0.26]
 [2.61]
 [0.47]
 [0.34]
 [0.27]
 [0.37]
 [0.26]
 [0.29]
 [0.22]
 [0.42]
 [0.5 ]
 [0.29]
 [0.26]
 [0.34]
 [0.29]
 [0.28]
 [0.2 ]
 [0.34]
 [0.27]
 [3.56]
 [0.32]
 [3.  ]
 [0.3 ]
 [0.27]
 [0.21]
 [2.75]
 [0.32]
 [2.91]
 [0.22]
 [0.32]
 [0.39]
 [0.21]
 [0.2 ]
 [0.26]
 [0.31]
 [0.19]
 [0.28]
 [0.41]
 [2.02]
 [0.32]
 [0.19]
 [1.45]
 [0.37]
 [3.18]
 [2.  ]
 [0.42]
 [1.28]
 [0.37]
 [0.21]
 [0.27]
 [0.21]
 [0.13]
 [0.34]
 [0.24]
 [0.43]
 [0.35]
 [0.43]
 [2.  ]
 [2.2 ]
 [2.  ]
 [0.61]
 [0.22]
 [0.3 ]
 [0.43]
 [0.4 ]
 [0.48]
 [0.42]
 [0.52]
 [0.5 ]
 [0.58]
 [0.25]
 [0.17]
 [0.32]
 [0.14]
 [0.29]
 [0.24]
 [0.45]
 [0.26]
 [0.29]
 [0.34]
 [0.37]
 [0.32]
 [0.66]
 [0.37]
 [0.48]
 [0.39]
 [0.29]
 [0.24]
 [2.  ]
 [0.6 ]
 [0.42]
 [0.43]
 [0.52]
 [0.3 ]
 [1.61]
 [0.43]
 [2.  ]
 [0.32]
 [0.47]


In [ ]:
print("Standard deviation:Computed row-wise:");
stdData = scores.std(axis=1);
print(stdData);

Standard deviation:Computed row-wise:
0      282.840872
1      278.848975
2      314.548639
3      393.109735
4      195.274640
          ...    
173    196.160444
174    198.906389
175    221.684271
176    223.058533
177    148.493305
Length: 178, dtype: float64


In [ ]:
Table_mean = np.nanmean(scores.values)
Table_median = np.nanmedian(scores.values)
Table_std = np.nanstd(scores.values)
print("Table mean:")
print(Table_mean)
print("Table median:")
print(Table_median)
print("Table std:")
print(Table_std)

Table mean:
64.33398715850723
Table median:
2.6
Table std:
208.61735837075227


In [ ]:
df = np.array(scores)
vals,counts = np.unique(df,return_counts=True)
index = np.argmax(counts)
Table_mode = vals[index]
print("Table mode:")
print(Table_mode)
listOfUniqueValues = zip(vals,counts)
print('Unique Values along with occurrence Count')
# Iterate over the zip object
for elem in listOfUniqueValues:
   print(elem[0] , ' Occurs : ' , elem[1], ' times')

Table mode:
2.0
Unique Values along with occurrence Count
0.13  Occurs :  1  times
0.14  Occurs :  2  times
0.17  Occurs :  5  times
0.19  Occurs :  2  times
0.2  Occurs :  2  times
0.21  Occurs :  6  times
0.22  Occurs :  6  times
0.24  Occurs :  7  times
0.25  Occurs :  2  times
0.26  Occurs :  11  times
0.27  Occurs :  8  times
0.28  Occurs :  5  times
0.29  Occurs :  10  times
0.3  Occurs :  8  times
0.31  Occurs :  2  times
0.32  Occurs :  9  times
0.33  Occurs :  1  times
0.34  Occurs :  9  times
0.35  Occurs :  1  times
0.37  Occurs :  8  times
0.39  Occurs :  5  times
0.4  Occurs :  8  times
0.41  Occurs :  2  times
0.42  Occurs :  6  times
0.43  Occurs :  11  times
0.44  Occurs :  1  times
0.45  Occurs :  3  times
0.47  Occurs :  6  times
0.48  Occurs :  6  times
0.49  Occurs :  1  times
0.5  Occurs :  7  times
0.51  Occurs :  1  times
0.52  Occurs :  6  times
0.53  Occurs :  7  times
0.54  Occurs :  1  times
0.55  Occurs :  4  times
0.56  Occurs :  4  times
0.57  Occurs :  6 

2.1. Take the ‘alcohol’ and ‘Proline’ as the features from the
‘wine.csv’ dataset and calculate the pearson correlation for the
same.

In [ ]:
print(scores['Alcohol'].corr(scores['Proline']))

0.6437200371782135


2.2. Take any 5 features from the ‘wine.csv’ datasets and load them in
a matrix. Thereafter, create the covariance matrix of the same.

In [ ]:
df2 = scores.sample(n = 5, axis = 'columns')
print(df2)

     Alcohol  Proline  Proanth  Flavanoids   Hue
0      14.23     1065     2.29        3.06  1.04
1      13.20     1050     1.28        2.76  1.05
2      13.16     1185     2.81        3.24  1.03
3      14.37     1480     2.18        3.49  0.86
4      13.24      735     1.82        2.69  1.04
..       ...      ...      ...         ...   ...
173    13.71      740     1.06        0.61  0.64
174    13.40      750     1.41        0.75  0.70
175    13.27      835     1.35        0.69  0.59
176    13.17      840     1.46        0.68  0.60
177    14.13      560     1.35        0.76  0.61

[178 rows x 5 columns]


In [ ]:
mat = df2.to_numpy()
print(mat)

[[1.423e+01 1.065e+03 2.290e+00 3.060e+00 1.040e+00]
 [1.320e+01 1.050e+03 1.280e+00 2.760e+00 1.050e+00]
 [1.316e+01 1.185e+03 2.810e+00 3.240e+00 1.030e+00]
 [1.437e+01 1.480e+03 2.180e+00 3.490e+00 8.600e-01]
 [1.324e+01 7.350e+02 1.820e+00 2.690e+00 1.040e+00]
 [1.420e+01 1.450e+03 1.970e+00 3.390e+00 1.050e+00]
 [1.439e+01 1.290e+03 1.980e+00 2.520e+00 1.020e+00]
 [1.406e+01 1.295e+03 1.250e+00 2.510e+00 1.060e+00]
 [1.483e+01 1.045e+03 1.980e+00 2.980e+00 1.080e+00]
 [1.386e+01 1.045e+03 1.850e+00 3.150e+00 1.010e+00]
 [1.410e+01 1.510e+03 2.380e+00 3.320e+00 1.250e+00]
 [1.412e+01 1.280e+03 1.570e+00 2.430e+00 1.170e+00]
 [1.375e+01 1.320e+03 1.810e+00 2.760e+00 1.150e+00]
 [1.475e+01 1.150e+03 2.810e+00 3.690e+00 1.250e+00]
 [1.438e+01 1.547e+03 2.960e+00 3.640e+00 1.200e+00]
 [1.363e+01 1.310e+03 1.460e+00 2.910e+00 1.280e+00]
 [1.430e+01 1.280e+03 1.970e+00 3.140e+00 1.070e+00]
 [1.383e+01 1.130e+03 1.720e+00 3.400e+00 1.130e+00]
 [1.419e+01 1.680e+03 1.860e+00 3.930e+00 1.23

In [ ]:
print("Covariance matrix:")
print(np.cov(mat))

Covariance matrix:
[[224682.25633  221624.72671  250135.789385 ... 176179.70925
  177238.713615 117839.7855  ]
 [221624.72671  218608.97342  246732.041195 ... 173781.955925
  174826.550205 116235.5912  ]
 [250135.789385 246732.041195 278474.23717  ... 196137.1317
  197316.21183  131186.07405 ]
 ...
 [176179.70925  173781.955925 196137.1317   ... 138149.3944
  138979.699075  92405.469725]
 [177238.713615 174826.550205 197316.21183  ... 138979.699075
  139815.00432   92960.6523  ]
 [117839.7855   116235.5912   131186.07405  ...  92405.469725
   92960.6523    61812.81115 ]]
